### PR TITLE
feature/add-page-param-for-folders

### PR DESCRIPTION
**Pull request by brandonpark**
## Changes
1. Added pagination support for folders and child folders
2. Updated read me with page parameter
3. Fixed markdown formatting issues

### CODE REVIEW

**Comment by tacovoyager** [comment]
Honestly I have no idea what I'm looking at. I don't know PHP well enough to review this.

@seanbehan can you take a look? Also this can be an opportunity to take a step back and assess if we're getting value from using this ancient in-house written PHP SDK. The contractor dev opted to use it because it supposedly saved them time, I am severely doubting this ended up being accurate. If there's a relatively low-effort way to sidestep the SDK completely, I fully support it.

On the other hand, if this PR represents a good set of changes that will be helpful for the WP Plugin for the foreseeable future, then I'm all for it. Relying on you guys to give me the information to make good decisions here. I don't want to have a conversation in 6 months about scrapping the usage of this SDK.

**Review by seanbehan — COMMENTED** [review]
Brandon any idea why the diff on this isn't showing specific changes? Indentation maybe?

**Comment by brandonpark** [comment]
> Brandon any idea why the diff on this isn't showing specific changes? Indentation maybe?

@seanbehan Yeah, click the gear glyph and check the hide whitespace option to see the two actual changes
image

**Comment by seanbehan** [comment]
Ah that feature not supported on mobile. Will try that tomorrow at my desktop. Thanks!

**Comment by brandonpark** [comment]
@justinperkins 

Re: moving away from the PHP SDK - if there is no need or desire to provide one for external users, it is really just extra work for us. Having this as a dependency within WordPress plugin provides no value to us (the internal dev team).

@seanbehan what do you think?

**Comment by seanbehan** [comment]
The issue this PR fixes is related to breaking changes in the folders API, requiring the page param. 

In regard to WP, I'd like to try updating Guzzle first. That dependency is really old and bumping it to the latest version could be the fastest path to get everything working on PHP 8. 

Making requests w/vanilla PHP is probably easier than using Guzzle. However, we'd have to rewrite all of the requests. So it will take time to do.

**Review by seanbehan — APPROVED** [review]
👍

**Pull request merged**
